theme: jekyll-theme-cayman
title: Joe Lambrecht
description: [About Me](https://github.com/joelambrecht/joelambrecht.github.io/blob/master/LambrechtJoeResume.pdf) | [Resume](https://github.com/joelambrecht/joelambrecht.github.io/blob/master/LambrechtJoeResume.pdf)
 
## My Projects
